### ISSUE TITLE
ImportError:cannot import cpu_soft_nms

### ISSUE THREAD

**Issue by kangmiao15** [bharatsingh430/soft-nms#2]
Hi.I tried your soft_nms in my py faster rcnn for tensorflow . I added the code  in nms_wrapper.py, cpu_nms.py  and config.py following your guide.But I got this error. Could your help me?
Traceback (most recent call last):
  File "./tools/train_net.py", line 16, in <module>
    from networks.factory import get_network
  File "/home/km/Faster-RCNN_TF/tools/../lib/networks/__init__.py", line 8, in <module>
    from .VGGnet_train import VGGnet_train
  File "/home/km/Faster-RCNN_TF/tools/../lib/networks/VGGnet_train.py", line 2, in <module>
    from networks.network import Network
  File "/home/km/Faster-RCNN_TF/tools/../lib/networks/network.py", line 5, in <module>
    from rpn_msr.proposal_layer_tf import proposal_layer as proposal_layer_py
  File "/home/km/Faster-RCNN_TF/tools/../lib/rpn_msr/proposal_layer_tf.py", line 13, in <module>
    from fast_rcnn.nms_wrapper import nms,soft_nms
  File "/home/km/Faster-RCNN_TF/tools/../lib/fast_rcnn/nms_wrapper.py", line 10, in <module>
    from nms.cpu_nms import cpu_nms,cpu_soft_nms
ImportError: cannot import name cpu_soft_nms

**Comment by navaneethbodla** [comment]
There was an import error issue that was closed in the recent commit. Refer to : https://github.com/bharatsingh430/soft-nms/issues/1 

Are you using the latest code and did you compile your lib folder ?

**Comment by kangmiao15** [comment]
Thank you.I have resolved it.  cd to lib,and make in shell .By the way,how to use the soft-nms with gpu?

**Comment by bharatsingh430** [comment]
We have not released the GPU version yet. It will be released in a month or so.

**Comment by kangmiao15** [comment]
Looking forward to your outstanding work.

**Comment by zengjianyou** [comment]
hi,I also tried your soft_nms in my py faster rcnn for caffe,i am a new user.Can i succeed when i replace  nms_wrapper.py, cpu_nms.py and config.py in the py-faster-rcn"s lib  to  your corresponding file. please help

**Comment by niuniu111** [comment]
How to use softnms under windows? Please help
